spring.application.name=validade-member
doc-application.description=Avaliacao tecnica SICRED
doc-application.version=v1

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.path=swagger-ui.html